### PR TITLE
added choc hotswap footprint

### PR DESCRIPTION
**Pull request by AaronDovTurkel**
Dont know if i need separate nets for pads and pins?

### CODE REVIEW

**Comment by mrzealot** [comment]
The same observations from #15 apply here as well. Also, while I'm not 100% sure, I don't think a switch needs separate from/to nets. Please check a "real" example, tho, to make sure.

**Comment by AaronDovTurkel** [comment]
I looked at my microdox pcb and they just have switches lol no reg pins

**Comment by AaronDovTurkel** [comment]
@mrzealot This may be ready to go...

**Comment by mrzealot** [comment]
Did some git magic, so this is merged now, even tho GH doesn't recognize it. Thanks a bunch!

**Pull request closed without merging**
