### PR TITLE
Corrections to footprint names in reference

### PR DESCRIPTION
**Pull request by brow**
I got this error when trying to use the footprint type `button`:

```
Error: Field "pcbs.main.footprints.reset.type" should be one of [mx, alps, choc, diode, promicro, slider, reset, rgb, jstph, pad]!
```

### CODE REVIEW

**Comment by mrzealot** [comment]
Reset is indeed this way right now, but I wonder if changing it to `button` to match the docs wouldn't be better than just "admitting defeat" and adjusting the docs? Also, while `pin` and `hole` are really not implemented (yet?), `pad` is **not** `pin`. Also also, now that I took a look, `pad` actually has a lot more undocumented params. Could you please include those in this PR, too? We can discuss on Discord, if needed...

**Comment by brow** [comment]
Sure! Just to make sure we're on the same page, I'll:
* Add `pad` to the doc
* Remove `pin` and `hole` from `reference.md` and `schema.json`
* Rename `reset` to `button` in the implementation and in `test/fixtures/absolem.yaml`

Let me know if any of that doesn't sound right. I don't understand yet what `pad`s are and what purpose the `pad`s in the Absolem PCB have, but I can ask you about that in Discord.

**Comment by mrzealot** [comment]
Sounds good to me! No need to bother with the fixture stuff, tho, as it is really old anyway... Proper testing is just gonna have to be its own thing down the line.

**Comment by mrzealot** [comment]
Wow, this is old, and we completely forgot about it... But nevermind, I just solved this by referencing the actual footprints folder from the docs, so it's always in sync.

**Pull request closed without merging**
